# Generated by Django 3.1.4 on 2020-12-29 13:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_auto_20201229_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='bodyType',
            field=models.TextField(choices=[('Sedan', 'Sedan'), ('Hathcback', 'Hathcback'), ('Suv', 'Suv'), ('Diğer', 'Diğer'), ('Crossover', 'CrossOver')], verbose_name='Kasa'),
        ),
        migrations.AlterField(
            model_name='article',
            name='fuelType',
            field=models.TextField(choices=[('Dizel', 'Dizel'), ('Hybrid', 'Hybrid'), ('Benzin Lpg', 'Benzin Lpg'), ('Elektrik', 'Elektrik'), ('Benzin', 'Benzin')], verbose_name='Yakıt'),
        ),
        migrations.AlterField(
            model_name='article',
            name='year',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(2021), django.core.validators.MinValueValidator(1980)], verbose_name='Yıl'),
        ),
    ]
