# Generated by Django 3.1.4 on 2020-12-29 16:04

import ckeditor.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_auto_20201229_1647'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='Cc',
        ),
        migrations.RemoveField(
            model_name='article',
            name='damage',
        ),
        migrations.RemoveField(
            model_name='article',
            name='date',
        ),
        migrations.RemoveField(
            model_name='article',
            name='hPower',
        ),
        migrations.RemoveField(
            model_name='article',
            name='plate',
        ),
        migrations.AlterField(
            model_name='article',
            name='bodyType',
            field=models.TextField(choices=[('Diğer', 'Diğer'), ('Hathcback', 'Hathcback'), ('Suv', 'Suv'), ('Crossover', 'CrossOver'), ('Sedan', 'Sedan')], verbose_name='Kasa'),
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Detay'),
        ),
        migrations.AlterField(
            model_name='article',
            name='engine',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Motor'),
        ),
        migrations.AlterField(
            model_name='article',
            name='fuelType',
            field=models.TextField(choices=[('Hybrid', 'Hybrid'), ('Elektrik', 'Elektrik'), ('Benzin Lpg', 'Benzin Lpg'), ('Benzin', 'Benzin'), ('Dizel', 'Dizel')], verbose_name='Yakıt'),
        ),
        migrations.AlterField(
            model_name='article',
            name='variant',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Paket'),
        ),
        migrations.AlterField(
            model_name='article',
            name='year',
            field=models.PositiveIntegerField(default=2020, validators=[django.core.validators.MaxValueValidator(2021), django.core.validators.MinValueValidator(1980)], verbose_name='Yıl'),
        ),
    ]
