# Generated by Django 3.1.4 on 2020-12-29 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_auto_20201229_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='bodyType',
            field=models.TextField(choices=[('Crossover', 'CrossOver'), ('Diğer', 'Diğer'), ('Hathcback', 'Hathcback'), ('Suv', 'Suv'), ('Sedan', 'Sedan')], verbose_name='Kasa'),
        ),
        migrations.AlterField(
            model_name='article',
            name='fuelType',
            field=models.TextField(choices=[('Benzin', 'Benzin'), ('Hybrid', 'Hybrid'), ('Dizel', 'Dizel'), ('Elektrik', 'Elektrik'), ('Benzin Lpg', 'Benzin Lpg')], verbose_name='Yakıt'),
        ),
    ]
