# Generated by Django 3.1.4 on 2020-12-29 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0010_auto_20201229_1925'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articleimage',
            old_name='article',
            new_name='car',
        ),
        migrations.AlterField(
            model_name='article',
            name='bodyType',
            field=models.TextField(choices=[('Crossover', 'CrossOver'), ('Hathcback', 'Hathcback'), ('Sedan', 'Sedan'), ('Suv', 'Suv'), ('Diğer', 'Diğer')], verbose_name='Kasa'),
        ),
        migrations.AlterField(
            model_name='article',
            name='fuelType',
            field=models.TextField(choices=[('Benzin', 'Benzin'), ('Hybrid', 'Hybrid'), ('Benzin Lpg', 'Benzin Lpg'), ('Elektrik', 'Elektrik'), ('Dizel', 'Dizel')], verbose_name='Yakıt'),
        ),
    ]
