# Generated by Django 3.1.4 on 2020-12-29 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0011_auto_20201229_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='bodyType',
            field=models.TextField(choices=[('Sedan', 'Sedan'), ('Suv', 'Suv'), ('Diğer', 'Diğer'), ('Hathcback', 'Hathcback'), ('Crossover', 'CrossOver')], verbose_name='Kasa'),
        ),
        migrations.AlterField(
            model_name='article',
            name='fuelType',
            field=models.TextField(choices=[('Dizel', 'Dizel'), ('Hybrid', 'Hybrid'), ('Benzin Lpg', 'Benzin Lpg'), ('Benzin', 'Benzin'), ('Elektrik', 'Elektrik')], verbose_name='Yakıt'),
        ),
    ]
