# Generated by Django 3.1.4 on 2020-12-29 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0012_auto_20201229_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='bodyType',
            field=models.TextField(choices=[('Suv', 'Suv'), ('Hathcback', 'Hathcback'), ('Crossover', 'CrossOver'), ('Diğer', 'Diğer'), ('Sedan', 'Sedan')], verbose_name='Kasa'),
        ),
        migrations.AlterField(
            model_name='article',
            name='fuelType',
            field=models.TextField(choices=[('Benzin', 'Benzin'), ('Dizel', 'Dizel'), ('Hybrid', 'Hybrid'), ('Benzin Lpg', 'Benzin Lpg'), ('Elektrik', 'Elektrik')], verbose_name='Yakıt'),
        ),
        migrations.AlterModelTable(
            name='article',
            table=None,
        ),
        migrations.AlterModelTable(
            name='articleimage',
            table=None,
        ),
    ]
