# Generated by Django 3.1.4 on 2020-12-30 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0013_auto_20201229_1948'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='pic',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Fotoğraf'),
        ),
        migrations.AddField(
            model_name='article',
            name='transmission',
            field=models.TextField(choices=[('Benzin Lpg', 'Benzin Lpg'), ('Benzin', 'Benzin'), ('Hybrid', 'Hybrid'), ('Dizel', 'Dizel'), ('Elektrik', 'Elektrik')], default=4, verbose_name='Vites'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='bodyType',
            field=models.TextField(choices=[('Suv', 'Suv'), ('Hathcback', 'Hathcback'), ('Diğer', 'Diğer'), ('Crossover', 'CrossOver'), ('Sedan', 'Sedan')], verbose_name='Kasa'),
        ),
        migrations.AlterField(
            model_name='article',
            name='fuelType',
            field=models.TextField(choices=[('Benzin Lpg', 'Benzin Lpg'), ('Benzin', 'Benzin'), ('Hybrid', 'Hybrid'), ('Dizel', 'Dizel'), ('Elektrik', 'Elektrik')], verbose_name='Yakıt'),
        ),
        migrations.DeleteModel(
            name='ArticleImage',
        ),
    ]
