# Generated by Django 3.1.4 on 2021-01-01 19:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0014_auto_20201230_1240'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameSurname', models.CharField(max_length=25, verbose_name='Ad Soyad')),
                ('replyOption', models.TextField(choices=[('Mail', 'Mail'), ('Telefon', 'Telefon')], verbose_name='Nasıl dönüş yapalım')),
                ('phone', models.PositiveIntegerField(verbose_name='Telefon')),
                ('mail', models.PositiveIntegerField(verbose_name='Mail')),
                ('subject', models.CharField(max_length=20, verbose_name='Konu')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Tarih')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Tarih'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='bodyType',
            field=models.TextField(choices=[('Hathcback', 'Hathcback'), ('Crossover', 'CrossOver'), ('Sedan', 'Sedan'), ('Diğer', 'Diğer'), ('Suv', 'Suv')], verbose_name='Kasa'),
        ),
        migrations.AlterField(
            model_name='article',
            name='fuelType',
            field=models.TextField(choices=[('Benzin', 'Benzin'), ('Elektrik', 'Elektrik'), ('Dizel', 'Dizel'), ('Benzin Lpg', 'Benzin Lpg'), ('Hybrid', 'Hybrid')], verbose_name='Yakıt'),
        ),
        migrations.AlterField(
            model_name='article',
            name='transmission',
            field=models.TextField(choices=[('Benzin', 'Benzin'), ('Elektrik', 'Elektrik'), ('Dizel', 'Dizel'), ('Benzin Lpg', 'Benzin Lpg'), ('Hybrid', 'Hybrid')], verbose_name='Vites'),
        ),
    ]
