# Generated by Django 3.1.4 on 2021-01-01 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0017_auto_20210101_2245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='bodyType',
            field=models.TextField(choices=[('Crossover', 'CrossOver'), ('Diğer', 'Diğer'), ('Hathcback', 'Hathcback'), ('Suv', 'Suv'), ('Sedan', 'Sedan')], verbose_name='Kasa'),
        ),
        migrations.AlterField(
            model_name='article',
            name='fuelType',
            field=models.TextField(choices=[('Benzin', 'Benzin'), ('Elektrik', 'Elektrik'), ('Benzin Lpg', 'Benzin Lpg'), ('Hybrid', 'Hybrid'), ('Dizel', 'Dizel')], verbose_name='Yakıt'),
        ),
        migrations.AlterField(
            model_name='article',
            name='transmission',
            field=models.TextField(choices=[('Benzin', 'Benzin'), ('Elektrik', 'Elektrik'), ('Benzin Lpg', 'Benzin Lpg'), ('Hybrid', 'Hybrid'), ('Dizel', 'Dizel')], verbose_name='Vites'),
        ),
        migrations.AlterField(
            model_name='message',
            name='replyOption',
            field=models.TextField(choices=[('Telefon', 'Telefon'), ('Mail', 'Mail')], verbose_name='Nasıl dönüş yapalım'),
        ),
    ]
