# Generated by Django 3.1.4 on 2021-01-01 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0018_auto_20210101_2245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='bodyType',
            field=models.TextField(choices=[('Sedan', 'Sedan'), ('Suv', 'Suv'), ('Diğer', 'Diğer'), ('Crossover', 'CrossOver'), ('Hathcback', 'Hathcback')], verbose_name='Kasa'),
        ),
        migrations.AlterField(
            model_name='article',
            name='fuelType',
            field=models.TextField(choices=[('Benzin', 'Benzin'), ('Dizel', 'Dizel'), ('Hybrid', 'Hybrid'), ('Benzin Lpg', 'Benzin Lpg'), ('Elektrik', 'Elektrik')], verbose_name='Yakıt'),
        ),
        migrations.AlterField(
            model_name='article',
            name='transmission',
            field=models.TextField(choices=[('Benzin', 'Benzin'), ('Dizel', 'Dizel'), ('Hybrid', 'Hybrid'), ('Benzin Lpg', 'Benzin Lpg'), ('Elektrik', 'Elektrik')], verbose_name='Vites'),
        ),
        migrations.AlterField(
            model_name='message',
            name='replyOption',
            field=models.TextField(choices=[('Mail', 'Mail'), ('Telefon', 'Telefon')], verbose_name='Nasıl dönüş yapalım'),
        ),
    ]
