# Generated by Django 3.1.4 on 2021-01-01 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0019_auto_20210101_2245'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='isDone',
            field=models.BooleanField(default=False, verbose_name='Dönüş Yapıldı'),
        ),
        migrations.AlterField(
            model_name='article',
            name='bodyType',
            field=models.TextField(choices=[('Diğer', 'Diğer'), ('Crossover', 'CrossOver'), ('Sedan', 'Sedan'), ('Hathcback', 'Hathcback'), ('Suv', 'Suv')], verbose_name='Kasa'),
        ),
        migrations.AlterField(
            model_name='article',
            name='fuelType',
            field=models.TextField(choices=[('Hybrid', 'Hybrid'), ('Benzin Lpg', 'Benzin Lpg'), ('Benzin', 'Benzin'), ('Dizel', 'Dizel'), ('Elektrik', 'Elektrik')], verbose_name='Yakıt'),
        ),
        migrations.AlterField(
            model_name='article',
            name='transmission',
            field=models.TextField(choices=[('Hybrid', 'Hybrid'), ('Benzin Lpg', 'Benzin Lpg'), ('Benzin', 'Benzin'), ('Dizel', 'Dizel'), ('Elektrik', 'Elektrik')], verbose_name='Vites'),
        ),
        migrations.AlterField(
            model_name='message',
            name='mail',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Mail'),
        ),
        migrations.AlterField(
            model_name='message',
            name='phone',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Telefon'),
        ),
        migrations.AlterField(
            model_name='message',
            name='replyOption',
            field=models.TextField(choices=[('Telefon', 'Telefon'), ('Mail', 'Mail')], verbose_name='Nasıl dönüş yapalım'),
        ),
        migrations.AlterField(
            model_name='message',
            name='subject',
            field=models.TextField(max_length=20, verbose_name='Konu'),
        ),
    ]
