# Generated by Django 3.1.4 on 2021-01-02 15:20

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0020_auto_20210101_2259'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='notes',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Notlar'),
        ),
        migrations.AlterField(
            model_name='article',
            name='bodyType',
            field=models.TextField(choices=[('Diğer', 'Diğer'), ('Hathcback', 'Hathcback'), ('Suv', 'Suv'), ('Sedan', 'Sedan'), ('Crossover', 'CrossOver')], verbose_name='Kasa'),
        ),
        migrations.AlterField(
            model_name='article',
            name='fuelType',
            field=models.TextField(choices=[('Benzin', 'Benzin'), ('Elektrik', 'Elektrik'), ('Dizel', 'Dizel'), ('Benzin Lpg', 'Benzin Lpg'), ('Hybrid', 'Hybrid')], verbose_name='Yakıt'),
        ),
        migrations.AlterField(
            model_name='article',
            name='transmission',
            field=models.TextField(choices=[('Benzin', 'Benzin'), ('Elektrik', 'Elektrik'), ('Dizel', 'Dizel'), ('Benzin Lpg', 'Benzin Lpg'), ('Hybrid', 'Hybrid')], verbose_name='Vites'),
        ),
        migrations.AlterField(
            model_name='message',
            name='phone',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='Telefon'),
        ),
    ]
