# Generated by Django 3.1.4 on 2021-01-03 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0021_auto_20210102_1820'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='highlighted',
            field=models.BooleanField(default=False, verbose_name='Öne Çıkar'),
        ),
        migrations.AlterField(
            model_name='article',
            name='bodyType',
            field=models.TextField(choices=[('Crossover', 'CrossOver'), ('Diğer', 'Diğer'), ('Sedan', 'Sedan'), ('Suv', 'Suv'), ('Hathcback', 'Hathcback')], verbose_name='Kasa'),
        ),
        migrations.AlterField(
            model_name='article',
            name='fuelType',
            field=models.TextField(choices=[('Elektrik', 'Elektrik'), ('Dizel', 'Dizel'), ('Benzin', 'Benzin'), ('Hybrid', 'Hybrid'), ('Benzin Lpg', 'Benzin Lpg')], verbose_name='Yakıt'),
        ),
        migrations.AlterField(
            model_name='article',
            name='transmission',
            field=models.TextField(choices=[('Elektrik', 'Elektrik'), ('Dizel', 'Dizel'), ('Benzin', 'Benzin'), ('Hybrid', 'Hybrid'), ('Benzin Lpg', 'Benzin Lpg')], verbose_name='Vites'),
        ),
        migrations.AlterField(
            model_name='message',
            name='replyOption',
            field=models.TextField(choices=[('Mail', 'Mail'), ('Telefon', 'Telefon')], verbose_name='Nasıl dönüş yapalım'),
        ),
    ]
