# Generated by Django 3.1.4 on 2021-01-03 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0022_auto_20210103_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='bodyType',
            field=models.TextField(choices=[('Suv', 'Suv'), ('Crossover', 'CrossOver'), ('Diğer', 'Diğer'), ('Sedan', 'Sedan'), ('Hathcback', 'Hathcback')], verbose_name='Kasa'),
        ),
        migrations.AlterField(
            model_name='article',
            name='fuelType',
            field=models.TextField(choices=[('Dizel', 'Dizel'), ('Hybrid', 'Hybrid'), ('Elektrik', 'Elektrik'), ('Benzin Lpg', 'Benzin Lpg'), ('Benzin', 'Benzin')], verbose_name='Yakıt'),
        ),
        migrations.AlterField(
            model_name='article',
            name='transmission',
            field=models.TextField(choices=[('Otomatik', 'Otomatik'), ('Manuel', 'Manuel'), ('Yarı Otomatik', 'Yarı Otomatik')], verbose_name='Vites'),
        ),
    ]
