# Generated by Django 3.1.4 on 2021-01-10 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0024_auto_20210110_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='bodyType',
            field=models.TextField(choices=[('Crossover', 'CrossOver'), ('Suv', 'Suv'), ('Sedan', 'Sedan'), ('Diğer', 'Diğer'), ('Hathcback', 'Hathcback')], verbose_name='Kasa'),
        ),
        migrations.AlterField(
            model_name='article',
            name='fuelType',
            field=models.TextField(choices=[('Dizel', 'Dizel'), ('Elektrik', 'Elektrik'), ('Benzin', 'Benzin'), ('Hybrid', 'Hybrid'), ('Benzin Lpg', 'Benzin Lpg')], verbose_name='Yakıt'),
        ),
        migrations.AlterField(
            model_name='article',
            name='transmission',
            field=models.TextField(choices=[('Yarı Otomatik', 'Yarı Otomatik'), ('Manuel', 'Manuel'), ('Otomatik', 'Otomatik')], verbose_name='Vites'),
        ),
        migrations.AlterField(
            model_name='message',
            name='replyOption',
            field=models.TextField(blank=True, choices=[('Mail', 'Mail'), ('Telefon', 'Telefon')], default='Mail', null=True, verbose_name='Nasıl dönüş yapalım'),
        ),
    ]
